version: '3'

services:
  postgres:
    image: postgres:15
    container_name: note_app
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: note_app_db
    ports:
      - 5432:5432
    volumes:
      - .docker/postgres:/var/lib/postgresql/data
